// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P01_BillsPaymentSystem.Data;

#nullable disable

namespace P01_BillsPaymentSystem.Data.Migrations
{
    [DbContext(typeof(BillsPaymentSystemContext))]
    [Migration("20230519183640_01")]
    partial class _01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.BankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Balance")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("BankAccountId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            BankAccountId = new Guid("56eef454-43b7-423b-82a1-f2f037fb0715"),
                            Balance = 2398.355037420498100m,
                            BankName = "Lodge Universal",
                            SwiftCode = "728"
                        },
                        new
                        {
                            BankAccountId = new Guid("6755bfa3-0918-4304-89c8-2ff90d7c1fe2"),
                            Balance = 9211.565137879586800m,
                            BankName = "Buckinghamshire deposit Regional",
                            SwiftCode = "109"
                        },
                        new
                        {
                            BankAccountId = new Guid("a308f252-19f5-4210-a590-261c0acff7d7"),
                            Balance = 8257.86629626038400m,
                            BankName = "mobile",
                            SwiftCode = "562"
                        },
                        new
                        {
                            BankAccountId = new Guid("86c23800-c0ee-4a15-b4ac-c40eba775ad8"),
                            Balance = 3696.02815504962700m,
                            BankName = "Vanuatu Expanded redundant",
                            SwiftCode = "036"
                        },
                        new
                        {
                            BankAccountId = new Guid("f8d5ba05-f933-462e-91b9-b8b53a67f4bd"),
                            Balance = 8837.358287886226900m,
                            BankName = "North Carolina compressing driver",
                            SwiftCode = "462"
                        });
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.CreditCard", b =>
                {
                    b.Property<Guid>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpirationTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Limit")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MoneyOwed")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CreditCardId");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            CreditCardId = new Guid("b8edcdac-a6d9-41ea-b62d-48f0904f8353"),
                            ExpirationTime = new DateTime(2032, 7, 26, 1, 47, 37, 600, DateTimeKind.Local).AddTicks(6382),
                            Limit = 7605.075551269195000m,
                            MoneyOwed = 1351.900948261230000m
                        },
                        new
                        {
                            CreditCardId = new Guid("00798a00-a882-4af2-9093-ab7f822cf1d9"),
                            ExpirationTime = new DateTime(2030, 2, 17, 12, 19, 54, 354, DateTimeKind.Local).AddTicks(6661),
                            Limit = 3289.282970017546000m,
                            MoneyOwed = 9367.462648339110000m
                        },
                        new
                        {
                            CreditCardId = new Guid("0aa6cd06-1437-49fe-9492-844af8960eb9"),
                            ExpirationTime = new DateTime(2030, 7, 1, 14, 3, 51, 251, DateTimeKind.Local).AddTicks(2480),
                            Limit = 7095.353009019769000m,
                            MoneyOwed = 9529.472757036390000m
                        },
                        new
                        {
                            CreditCardId = new Guid("44ffae60-2f9a-41d0-ac89-7251910dc8dd"),
                            ExpirationTime = new DateTime(2024, 12, 30, 11, 26, 49, 71, DateTimeKind.Local).AddTicks(6881),
                            Limit = 3985.343487140356000m,
                            MoneyOwed = 5366.485504064230000m
                        },
                        new
                        {
                            CreditCardId = new Guid("21462c4b-eb60-4a7f-9062-11fe1625c1d5"),
                            ExpirationTime = new DateTime(2024, 4, 7, 7, 48, 10, 650, DateTimeKind.Local).AddTicks(9445),
                            Limit = 5552.720171514892000m,
                            MoneyOwed = 9277.626410303450000m
                        });
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreditCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .IsUnique()
                        .HasFilter("[BankAccountId] IS NOT NULL");

                    b.HasIndex("CreditCardId")
                        .IsUnique()
                        .HasFilter("[CreditCardId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("753962f8-40a5-4195-9738-ea414804ed75"),
                            CreditCardId = new Guid("b8edcdac-a6d9-41ea-b62d-48f0904f8353"),
                            Type = "CreditCard",
                            UserId = new Guid("171fd338-d1ca-4760-bdb4-7d4775e462fe")
                        },
                        new
                        {
                            Id = new Guid("064fb6df-ffa9-43a4-8121-006e7b93122a"),
                            CreditCardId = new Guid("0aa6cd06-1437-49fe-9492-844af8960eb9"),
                            Type = "CreditCard",
                            UserId = new Guid("a521d7e3-83db-4c23-8b11-cf8365192946")
                        },
                        new
                        {
                            Id = new Guid("aa2138f9-63db-4bf0-9f55-ecc5674909c8"),
                            BankAccountId = new Guid("6755bfa3-0918-4304-89c8-2ff90d7c1fe2"),
                            Type = "BankAccount",
                            UserId = new Guid("171fd338-d1ca-4760-bdb4-7d4775e462fe")
                        },
                        new
                        {
                            Id = new Guid("4c993dc3-76b1-4e28-8123-8b6f178ee26a"),
                            BankAccountId = new Guid("f8d5ba05-f933-462e-91b9-b8b53a67f4bd"),
                            Type = "BankAccount",
                            UserId = new Guid("9ead0c1a-54d4-416b-925a-546ed44daf24")
                        },
                        new
                        {
                            Id = new Guid("e37c91cc-891b-4561-b452-8b501e447dd5"),
                            CreditCardId = new Guid("21462c4b-eb60-4a7f-9062-11fe1625c1d5"),
                            Type = "CreditCard",
                            UserId = new Guid("171fd338-d1ca-4760-bdb4-7d4775e462fe")
                        });
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9e449b67-3b57-4433-a7cd-a9878e278d59"),
                            Email = "Madeline.Bruen@yahoo.com",
                            FirstName = "Madeline",
                            LastName = "Bruen",
                            Password = "mzwWiKBuYE"
                        },
                        new
                        {
                            UserId = new Guid("171fd338-d1ca-4760-bdb4-7d4775e462fe"),
                            Email = "Lorenzo73@hotmail.com",
                            FirstName = "Lorenzo",
                            LastName = "Greenholt",
                            Password = "kW8p68PhI2"
                        },
                        new
                        {
                            UserId = new Guid("47cb7ee7-9dac-412d-8a10-b5fb0535b30d"),
                            Email = "Jaime66@gmail.com",
                            FirstName = "Jaime",
                            LastName = "Rice",
                            Password = "x86XTg_yAs"
                        },
                        new
                        {
                            UserId = new Guid("9ead0c1a-54d4-416b-925a-546ed44daf24"),
                            Email = "Traci.Russel98@yahoo.com",
                            FirstName = "Traci",
                            LastName = "Russel",
                            Password = "oZWNbnMH1L"
                        },
                        new
                        {
                            UserId = new Guid("a521d7e3-83db-4c23-8b11-cf8365192946"),
                            Email = "Gustavo.Cole@gmail.com",
                            FirstName = "Gustavo",
                            LastName = "Cole",
                            Password = "mXObJa3E22"
                        });
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.PaymentMethod", b =>
                {
                    b.HasOne("P01_BillsPaymentSystem.Data.Models.BankAccount", "BankAccount")
                        .WithOne("PaymentMethod")
                        .HasForeignKey("P01_BillsPaymentSystem.Data.Models.PaymentMethod", "BankAccountId");

                    b.HasOne("P01_BillsPaymentSystem.Data.Models.CreditCard", "CreditCard")
                        .WithOne("PaymentMethod")
                        .HasForeignKey("P01_BillsPaymentSystem.Data.Models.PaymentMethod", "CreditCardId");

                    b.HasOne("P01_BillsPaymentSystem.Data.Models.User", "User")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.BankAccount", b =>
                {
                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.CreditCard", b =>
                {
                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("P01_BillsPaymentSystem.Data.Models.User", b =>
                {
                    b.Navigation("PaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
